site_name: Gitsheet
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: amber
      accent: orange
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode   
      primary: amber
      accent: orange
markdown_extensions:
  - attr_list
  - md_in_html
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_code_format
  # - pymdownx.tabbed:
  #     alternate_style: true
  #     combine_header_slug: true
  #     slugify: !!python/object/apply:pymdownx.slugs.slugify
  #       kwds:
  #         case: lower
# extra:
#   alternate:
#     - name: Français
#       link: /fr/
#       lang: fr
#     - name: English
#       link: /en/ 
#       lang: en
# Page tree
nav:
  - Home: index.md
  - Quick-Start:
    - Installation: install.md
    - SSH key: ssh_key.md
    - Basic commands: basic_commands.md
  - Most used commands: 
    - Most Used Commands: most_used_commands.md
    - Misc commands : misc_commands.md
  - Best Practices:
    - Conventions: conventions.md
    - Pre-commit: pre-commit.md
  - UI git:
    - VS Code : vscode.md
    - Github Desktop : github_desktop.md
    - Git GUI : git_gui.md
  - Common questions:
    - Common questions: common_questions.md
  - Pull requests:
    - Github: Github.md
    - Azure Devops: azure_devops.md
  - Tips: tips.md
  - Resources: resources.md
copyright: |
  &copy; 2024 <a href="https://github.com/quentinlegay"  target="_blank" rel="noopener">Quentin LEGAY, v0.0.1</a>

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/squidfunk


